### ISSUE TITLE
Please update nestjs-zod-prisma too

### ISSUE THREAD

**Issue by marmotz** [BenLorantfy/nestjs-zod#108]
nestjs-zod-prisma generate model and DTO from prisma schema using nestjs-zod.

Unfortunately, with nestjs-zod 4.x nestjs-zod-prisma does not work anymore because it using `nestjs-zod/z` instead of `@nest-zod/z`

**Comment by DavidVaness** [comment]
Would also appreciate it @BenLorantfy 🙏🏼

**Comment by BenLorantfy** [comment]
Hey @marmotz @DavidVaness , I'm not super familiar with `nestjs-zod-prisma` and I didn't get access to that repo.  Can you please explain the use-case for it? It feels unnecessary to couple nestjs to the prisma->zod generation. I also see a few other packages that are several times more popular than `nestjs-zod-prisma`:
- https://www.npmjs.com/package/zod-prisma 
- https://www.npmjs.com/package/prisma-zod-generator

Perhaps as a community we should move towards one of these packages to avoid fragmentation?

**Comment by BenLorantfy** [comment]
Closing for the reasons explained above

**Comment by DavidVaness** [comment]
> Closing for the reasons explained above

Sounds good 👍
