### ISSUE TITLE
Impossible to import nestjs-zod ESM required

### ISSUE THREAD

**Issue by Ephasme** [BenLorantfy/nestjs-zod#110]
When I try to use nestjs-zod I import it as usual and my nestjs project tells me :

```Error [ERR_REQUIRE_ESM]: require() of ES Module *** from *** not supported.```

How do I solve this? My current project has been configured by nestjs-cli and I did not modify the `ts-config.json` file or the `package.json` file myself.

**Comment by BenLorantfy** [comment]
@Ephasme do you have a minimal reproduction repo you could share?  nestjs uses CJS by default afaik so I'm surprised to see this error

**Comment by ChiuMungZitAlexander** [comment]
I believe nestjs that must run in CJS
