### ISSUE TITLE
FR: Log validation errors from `ZodSerializerDto`

### ISSUE THREAD

**Issue by maxijonson** [BenLorantfy/nestjs-zod#112]
I'm using `ZodSerializerDto` to validate the output of my endpoints. However, when the output is wrong, I get an error `500` (as I should), but can't figure out why it failed. Obviously, for security purposes, I believe that information should not be in the response, but it would be nice to see the error _somewhere_, like the console. 

I've literally started using `nestjs-zod` an hour ago, so maybe there's a way to extend `ZodSerializerDto` so that I can get this without needing a change from `nestjs-zod`? 👀

**Comment by BenLorantfy** [comment]
@maxijonson I exported `ZodSerializationException`, so you can log serialization errors like this:

https://github.com/BenLorantfy/nestjs-zod/blob/8e8d515f61353dcfb92aae030c155d3ea30faa1f/packages/example/src/http-exception.filter.ts#L1-L17


<img width="846" alt="image" src="https://github.com/user-attachments/assets/d7f88d88-3a45-48b9-a513-8e729bb62172">

See docs here: https://github.com/BenLorantfy/nestjs-zod?tab=readme-ov-file#logging-serialization-errors-using-zodserializationexception
